### ISSUE TITLE
[Design issue] Remove fields labeled HIE and HIT for MMIS APDs

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3685] opened 2022-01-07 21:30 UTC
The following fields/elements should be removed in order to implement an MMIS APD. 

**APD Overview** This is represented in #3316
- HIT Overview
- HIE Overview

**Activities**
- Funding source from Activity name (name/title on Activities Dashboard)
- Funding source in Activity Overview (this may already be represented in Figma for 3688)

**Proposed Budget** (Could be covered in #3380?) 
- HIT and HIE sections of Combined Activity Costs
- HIT Activities (Summary Budget Table)
- HIE Activities (Summary Budget Table)
- HIT and HIE quarterly Federal Share table
- Incentive Payment Table

### This task is done when...

- [x]  Remove HIE and HIT tables from Results of Previous Activities
- [x] Remove HIT and HIE tables from Proposed Budget
- [x] Remove Incentive Payments from Proposed Budget
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature
---

**Comment by aricka-lewis** [comment] 2022-02-03 21:29
expand MMIS program budget table per fed/state split (inside executive summary)

**Comment by akuas** [comment] 2022-09-26 14:40
For this ticket, we can include removing the HIT/HIE from the Results of Previous Activities. As for the former APD Overview, now State Priorities and Scope of APD, we have that page covered in terms of removing HITECH specific fields. We can address reviewing the existing fields and help text in 3316.

**Comment by akuas** [comment] 2022-09-28 19:20
For this ticket, I focused on removing HIE and HIT specific fields from our MMIS. I didn't address HITECH specific help text/examples or changing the structure/introducing new tables to the designs. Some of the HIE/HIT fields are already removed but the list of fields that need to be removed for MMIS are as follows.
1. APD Overview (HIT Overview and HIE Overview)
2. [Results of Previous Activities](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=970%3A11404): (HIE and HIT tables in Actual Expenditures and their total in the Grand Total). In the future, maybe we could consider if we need a grand total if there is only one funding source.
3. Activities Dashboard (Removing (HIT) from the Activity Name
4. Activity Overview : Program Type
5. Budget and FFP : Estimated Quarterly Expenditure. Removing this field is already reflected in [4304](https://github.com/CMSgov/eAPD/issues/4304)
6. [Proposed Budget ](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1003%3A12437): Incentive Payments

**Comment by akuas** [comment] 2022-09-28 19:24
Just to recap, with this ticket the design changed for Results of Previous Activities and Proposed Budget. I also checked the UI to check to see where we have HIE and HIT specific fields and confirmed they have been removed on figma. Any additions of MMIS specific fields are reflected in other tickets.

**Comment by akuas** [comment] 2022-09-28 19:26
@SGilliamA1M @jeromeleecms This ticket is ready for review. For this ticket we are focusing on HIE/HIT field removal, not the help text or any additions to the MMIS UI, so please let me know if I missed anything.

**Comment by SGilliamA1M** [comment] 2022-09-29 14:07
Thanks @akuas. 
Removal of HIE/HIT fields have been verified in Figma and changes look good.

**Comment by jeromeleecms** [comment] 2022-10-12 19:43
We also need to remove the HIT + HIE tables from the Executive Summary: Proposed Budget Tables.

It looks like the design reflects it already, but I don't see it reflected in the documentation for this ticket.

**Comment by jeromeleecms** [comment] 2022-10-19 15:18
New Dev ticket looks good. Closing!

**Closed by jeromeleecms** 2022-10-19 15:18 UTC
Labels: Design, medium
