### ISSUE TITLE
[Design issue] Add ability to lock an APD to Export and Submit page

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3696] opened 2022-01-11 17:38 UTC
Once an APD has gone through an Admin Check and no validation errors remain, an APD can be locked. 

Considerations:
- APD should be locked before submitting
- This section should only appear for those with lock permissions
- Provide a way for the user to verify that they are locking the APD
- Cannot submit until admin check is run and APD is locked
- Experience for non-submitters or those who don't have permission to lock and submit\

The updated flow is explained in [3757](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3757)

### This task is done when...

- [x]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature
---

**Comment by akuas** [comment] 2022-02-11 13:42
Design Sync Notes
1. Instead of having a new design for read only, the "preview this APD" button will open up pdf previews in a separate tab in the browser
2. We should know that they downloaded in the browser preview
3. Version numbers will increate the number when there is a change in the APD, not per download
4. If there is no change, the backend will pull in the pdf already created 
5. Dev: Need to figure out if there will be loading for the export pdf
6. We don't need the How to Export but it does not hurt to keep it 
7. Dev needs to revisit table of contents, if we no longer have the read only view, as it exists now
8: Design: Create a modal that this APD is locked down triggered in the same way as the "unable to save changes modal". The system will different if you cant save because it is locked

**Comment by akuas** [comment] 2022-02-11 16:39
[State Admin Export and Submit Designs](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7522%3A90455)

**Comment by akuas** [comment] 2022-02-11 16:40
[State Author Export APD Designs](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7523%3A90456)

**Comment by akuas** [comment] 2022-02-11 21:36
@jeromeleecms Can you please take a look at the designs. Since, the design sync, I have added a modal indicating that the APD is locked, removed the read only view and replaced it with a pdf preview, removed the how to export help drawer and replaced it with how to submit. I especially need help on the copy. In the how to submit this APD, I wanted to provide some guidance on how to make the APD administratively complete, but unfortunately Im having a hard time finding a document that lists all the criteria. I also wanted to spell out the beginning process of the review just in case users assume that process has changed with eAPD.

**Comment by akuas** [comment] 2022-02-14 13:24
@jeromeleecms Thanks, I will revise them now.

**Comment by akuas** [comment] 2022-02-16 14:05
1. I changed the hyperlink on the admin check information alert but the expected behavior is that the hyperlink will direct your to the Review APD page not that it will open the modal.
2. The button on the export apd page will be back to the review apd page and back to dashboard when the lock is complete
3. Instead of hyperlinking the CMS existing submission process, I pulled it out of the paragraph so that it looks less like a hyperlink that directs you to a different page and more like a help drawer.  I did like it being titled "How to submit your APD" because i felt it was easy to understand but CMS existing submission process also works.

**Comment by akuas** [comment] 2022-02-16 14:06
@aricka-lewis @jeromeleecms If there are no issues, I think this ticket is ready for dev.

**Comment by aricka-lewis** [comment] 2022-02-16 15:13
This looks good to me! I will update the modals on the dashboard work to reflect these changes as well. @akuas

**Comment by jeromeleecms** [comment] 2022-02-17 23:40
@akuas One small edit to the copy (remove the "the") and this looks good to go! ![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/88b329d3-444d-462b-a64f-698847aad1e3)

I'll reassign the ticket in the meantime.

**Comment by akuas** [comment] 2022-02-18 12:23
@jeromeleecms Thanks!

**Comment by thetif** [comment] 2022-02-28 20:24
added dev tickets #3834, #3836, #3837

**Closed** 2022-02-28 20:24 UTC
Labels: design, Medium
