### ISSUE TITLE
[Tech Debt] Consolidate web/src/app.js and web/src/app.dev.js files

### ISSUE THREAD

**Issue by radavis** [CMSgov/eAPD#2571] opened 2020-10-13 16:45 UTC
Merge code from `app.dev.js` into `app.js`. Use `NODE_ENV` or other environment variables to switch configuration.

### This task is done when...
 - [ ] code/configuration from `app.dev.js` is merged into `app.js`

**Comment by thetif** [comment] 2021-04-27 13:58
duplicate of #2443

**Closed by thetif** 2021-04-27 13:58 UTC
Labels: Refactor, Small, development
