### ISSUE TITLE
[Design Issue] Design options to keep the help drawer from covering the workspace

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3536] opened 2021-10-08 22:08 UTC
* Design a mechanism to easily expand and collapse the check or come up with a design that doesn’t cover the content of the page
* Talk with Ty about altering the help drawer component of the design system to not close all the way. 
* If that doesn't work, explore what our other options might be
* We don't necessarily want to just have a close and open button, because having the check running in the background all the time might not be the best experience

### This task is done when…

- [x] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product

**Comment by akuas** [comment] 2021-11-18 16:01
Below are my designs for the help drawer collapsed. The designs are submit to change.
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6515%3A40502

**Comment by akuas** [comment] 2021-11-18 17:26
I asked @ty whether we could modify the existing CMS design system help drawer to not close all the way. It looks like it wouldn't be possible to use the CMS design system to enable that. Ty mentioned it could be possible "to do some modifications to have it not close all the way" but we will likely need a custom component for the help drawer.

**Comment by akuas** [comment] 2021-11-18 18:39
Regarding the 2nd issue of not having the error check block the main content, Ty mentioned: 
1. "I'm not sure how we would achieve not covering the main content. The issue is that we can't count on everyone viewing the content at a fixed screen/window size. If you look at the cms design system example. You can slowly make your browser window size smaller and watch the drawer respond to the size (ultimately covering the whole windows). I know we are only aiming to support desktop size windows but I still don't think we can cram everything in."
2. "Here is a screenshot of the app viewed in a window with a width of 1280px. to add the drawer here without covering the content you'd have to fit it in the purple area. which seems pretty tight. alternatively we could re-do the layout such that the blue area shrinks to accommodate a larger purple area (drawer)." 
![image (2).png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/311a2671-f09c-468b-9511-9c6831f4b883)

**Comment by akuas** [comment] 2021-11-18 18:40
Also, regarding the 2nd issue of not having the error check block the main content, the CMS design system help drawer is responsive to an extent but it still blocks the main content.

**Comment by akuas** [comment] 2021-11-18 19:54
@jeromeleecms Please let me know what you think about this.

**Comment by jeromeleecms** [comment] 2021-11-18 21:12
1) I like the general look of the collapsed drawer. In the collapsed view, what do you think about it appearing like a modal that is slight offset from the top and right portion of the screen and then "dock" to the side when the drawer is expanded? 

2) User Interaction: How does the user interact with this mini drawer? Does the user click on a button to go to the next field that needs content? Or were you intending the button navigation to take the user to the next section (like the nav buttons at the end of each section of the app and the user would have to scroll manually to find any fields which are missing content?

3) Content
- The language "Now Working On" -- is that meant to indicate which section the user is in on the app? Should that line up with the side nav / or title on the page?
- The language "Specifically" -- The content of that section should line up with the label of the form field, right? I'm a bit on the fence about using the word "Field."

**Comment by akuas** [comment] 2021-11-24 13:13
@jeromeleecms Thanks Jerome, moving this back to in progress to revise the design.

**Comment by akuas** [comment] 2021-11-24 14:55
1) Yes, I like that idea of having the abridged/collapsed version move when the user scrolls like a modal. I'll note that interaction in the stickies on figma.

2) User Interaction: I was imagining that the button to proceed to the next section would be the next section that needs content, not necessarily the next page in the navigation. With the mini drawer, folks can view what page they are on and what fields are they need to complete. They can also expand to view the full admin check but once there are no tasks to complete they can close the drawer or navigate back to the Export and Submit page. It is basically a bare bones version of the full admin check and doesnt have the recently completed section. The button will direct users to the next page not field that needs work but like the #3534, we can revisit whether we want to guide users through the unanswered required fields by jumping/directing users to the fields that need attention. 

3) Content: From our discussion in the design sync, I will revise the content to better align with how information is presented in the full admin check. So 'Now Working On' and 'Specifically' would be replaced by some copy that indicates the page name and the fields to complete.

What term were you thinking of instead of using the word 'field'? @jeromeleecms

**Comment by akuas** [comment] 2021-11-24 19:53
Updated the [field grouping design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6515%3A40502) and the content. Please let me know if the content is clearer. Regarding the use of 'field' I think if everything else is fine, I think we can push this ticket forward and I can create an extra small ticket to replace that term in the help drawers and ask Caryn for assistance on the copy.

**Comment by akuas** [comment] 2021-11-24 19:55
For dev @thetif , the continue to next section will be an active button, so they can continue to the next section even if they are not done with the page that they are on. I'm imagining once they get to the last page in the navigation they have to do, the admin check will just loop back to the previous pages they had skipped by selecting the continue to the next section button. Feel free to let me know if that is unclear. 
We can meet next week to touch base on the validation work before dev starts working on it.

**Comment by NAretakis** [comment] 2021-12-02 16:14
@akuas  These look great! Let's make it happen, approved.

**Comment by akuas** [comment] 2021-12-21 16:38
@thetif Can we close this ticket?

**Comment by thetif** [comment] 2021-12-21 18:32
Let me make tickets for it really quickly. This work is just for displaying the help drawer and handling navigation between the sections, right? Also just to clarify, when you say

> so they can continue to the next section even if they are not done with the page that they are on

you mean the next section that has missing fields, right?

**Comment by thetif** [comment] 2021-12-21 19:03
also @akuas is that Incomplete Require Fields Total a link? and if so where does it go?

![](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/a37572cb-cebb-4bae-852c-5e8455b37a87)

**Comment by thetif** [comment] 2021-12-21 19:16
never mind, I see that this is just about where it should go not what it should look like

**Closed by thetif** 2021-12-21 19:16 UTC
Labels: design, Small

**Comment by akuas** [comment] 2021-12-21 21:45
@thetif Good callout on it looking like a link. I removed the underline to minimize confusion and yes, it doesn't direct you anywhere.
