### ISSUE TITLE
[Dev] Images not loading

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2845] opened 2021-02-04 18:04 UTC
Images are not displaying in the RTE because the cookies are being blocked on staging and production

### This task is done when…
This could include:
 - [ ] images are displaying

**Comment by thetif** [comment] 2021-02-16 21:35
@eStar386 can you verify that this is working in Staging too (you can use the same users that are in keybase) once you verified it you can move to to ready to review and tag Jerome and Jenn. Thanks!

**Comment by eStar386** [comment] 2021-02-17 19:37
@thetif Yes to both and NP!

**Comment by eStar386** [comment] 2021-02-19 15:20
@thetif , I added 2605 because this accessibility ticket directly impacts the image functionality.

**Comment by eStar386** [comment] 2021-02-22 18:57
Failed Accessibility Testing - There are two small accessibility issues in the RTE.

1. Wave Error - Steps to Reproduce Right click and select Wave. It shows a broken ARIA menu. 
2. Screenreader- Steps to Reproduce. Using voiceover, have the screenreader read the menu for the rich text editor. It reads all the menu items except for the paragraph - it goes div div div paragraph. 

Functional Issue:  There is a bug with the cookie being rejected or blocked. In these cases, it causes a 401 error and displays the following the unhelpful - the user needs to know to enable cookies to fully use the site.  Otherwise, they can't login and won't know why.
![image](https://user-images.githubusercontent.com/71447081/108755780-ac468d80-7515-11eb-8c76-d349a4a62c48.png)
Browser:Google
Steps To Reproduce:  
 1. Disable or Block the Eapd Cookie
 2. Login to the apd.
Result: The image above.

**Comment by eStar386** [comment] 2021-03-15 21:06
Documenting a known accessibility issue with the TinyMCE headers causing the above wave errors.

**Comment by eStar386** [comment] 2021-03-18 20:22
Documenting an exemption, there is an issue with certain file sizes and the user isn't notified of the issue. This may be fixed in #2941

**Closed** 2021-03-30 19:35 UTC
Labels: Medium, QA, Sev1, bug, development
