### ISSUE TITLE
Rotate AWS Access Keys

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3508] opened 2021-09-30 20:35 UTC
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/6531e795-8e39-41e5-94f6-3ff73d20949f)

**Comment by jeromeleecms** [comment] 2021-10-04 17:08
Duplicate of #3509

**Closed by jeromeleecms** 2021-10-04 17:08 UTC
Labels: development, DevOps
