### ISSUE TITLE
[Feature] Set up Cypress tests to run locally

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3226] opened 2021-06-28 21:17 UTC
**Description and related issues -**
Install Cypress into the application, create a single test, create a script that will run tests locally, and create a script that will run the tests in CI-mode.

### This task is done when…
- [x] cypress is install in the application
- [x] one cypress test has been created
- [x] there is a package.json script to run the tests locally

**Comment by cthulhuplus** [comment] 2021-07-07 14:22
@thetif I got it running locally using Docker, but it did require some additional steps. I don't know if having it work natively in Docker is part of the scope of this ticket. I can address this in the Cypress CI ticket if it is more inline with that.

**Comment by thetif** [comment] 2021-07-07 14:25
@cthulhuplus what extra steps did you have to do? I'm still looking into it, but it seems like to get the gui working, you do have to do extra steps that are dependent on your machine type.

**Comment by cthulhuplus** [comment] 2021-07-07 14:36
These steps on a fresh brand new container:
```
docker exec eapd_web_1 sh -c 'echo "deb-src  http://deb.debian.org/debian  stretch main" >> /etc/apt/sources.list'
docker exec eapd_web_1 apt-get update -y
docker exec eapd_web_1 apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
docker exec eapd_web_1 node_modules/.bin/cypress run
```
Cypress run prints out the results to the terminal window and gives you a summary at the end like this:
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/98f9efd2-9acd-48c8-8c69-3932e0c4bb10)

**Comment by cthulhuplus** [comment] 2021-07-09 18:26
Updated the Dockerfile so that cypress can be run via command line/Docker without additional steps

**Comment by cthulhuplus** [comment] 2021-07-13 19:46
@thetif I feel like the last checkbox here is sort of a duplicate of the larger ticket to do Cypress in the CI

**Closed** 2021-07-22 17:06 UTC
Labels: Small, development
